env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:markdown/recommended'
  - 'prettier'
plugins:
  - markdown
  - prettier
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
overrides:
  - files:
    - "**/*.md"
    processor: "markdown/markdown"
rules:
  prettier/prettier:
    - error
