env:
  browser: true
  commonjs: true
  es2022: true
extends:
  - 'eslint:recommended'
  - 'plugin:markdown/recommended'
  - 'prettier'
plugins:
  - markdown
  - prettier
parserOptions:
  sourceType: module
  ecmaVersion: 13
overrides:
  - files:
    - "**/*.md"
    processor: "markdown/markdown"
rules:
  prettier/prettier:
    - error
