/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "index",
    "whats-new-in-the-embedding-sdk",
    "upgrade",
    {
      type: "category",
      link: {
        type: "doc",
        id: "support-for-different-authentication-environments/support-for-different-authentication-environments",
      },
      label: "Support for Different Authentication Environments",
      items: [
        "support-for-different-authentication-environments/guest-authentication-mode-only",
        "support-for-different-authentication-environments/multiple-modes",
        "support-for-different-authentication-environments/authentication-saml",
        "support-for-different-authentication-environments/authentication-custom",
      ],
    },
    {
      type: "category",
      link: {
        type: "doc",
        id: "add-functionality/add-functionality",
      },
      label: "Add Functionality to an Embedded Dossier",
      items: [
        "add-functionality/add-nav",
        "add-functionality/add-event",
        "add-functionality/filters",
        "add-functionality/set-properties",
        "add-functionality/methods-and-properties",
        "add-functionality/custom-error-handling",
        "add-functionality/panel-stacks",
        "add-functionality/embed-vis",
        "add-functionality/attribute-element-selection",
        "add-functionality/authoring-library",
      ],
    },
    "workflow",
    "config",
  ],
};

module.exports = sidebars;
